# Generated by Django 2.2.16 on 2022-09-13 18:37

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20220913_1756'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='no_self_folowwing',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user__exact=django.db.models.expressions.F('author')), name='no_self_following'),
        ),
    ]
