# Generated by Django 2.2.16 on 2022-09-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20220917_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='Фотографии, жанр которых не выбран', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='others', unique=True, verbose_name='Человекочитаемый идентификатор'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(default='Остальное', max_length=200, verbose_name='Название'),
        ),
    ]
